title: Wonderful
author: GitHub User
email: oofworld6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Whats up guys. Hope your liking the website so far...
  We are still making changes to our website, so stay updated!

# social links
instagram username: sx_illustriiious
github_username:  TobiasK53

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
